const modeConfig = {
  contacts: {
    sendButtonId: 'enviarMensajes',
    forceSendButtonId: 'forzarEnvioMensajes',
    selectFilesButtonId: 'selectFiles',
    messageFieldId: 'mensaje',
    delayMinId: 'delayMin',
    delayMaxId: 'delayMax',
    unitDelayMinId: 'unitDelayMin',
    unitDelayMaxId: 'unitDelayMax',
    complianceModeId: 'complianceModeContacts',
    riskProfileId: 'riskProfileContacts',
    riskIndicatorId: 'riskIndicatorContacts',
    riskReasonId: 'riskReasonContacts',
    riskSuggestionId: 'safeSuggestionContacts',
    riskScoreId: 'riskScoreContacts',
    applySafeConfigId: 'applySafeConfigContacts',
    targetCounterId: 'targetCounterContacts',
    clearSentTargetsId: 'clearSentContacts',
    sendFilesFirstId: 'sendFilesFirstContacts',
    sendTextFirstId: 'sendTextFirstContacts',
    sendMessageSplitId: 'sendMessageSplitContacts',
    sendMessageSplitOptionId: 'sendMessageSplitOptionContacts',
    maxFiles: 3,
    progressLabel: 'Enviando mensajes a contactos...',
    successLabel: 'mensajes enviados correctamente'
  },
  groups: {
    sendButtonId: 'enviarGrupos',
    forceSendButtonId: 'forzarEnvioGrupos',
    selectFilesButtonId: 'selectFilesGrupo',
    messageFieldId: 'mensajeGrupo',
    delayMinId: 'delayMinGrupo',
    delayMaxId: 'delayMaxGrupo',
    unitDelayMinId: 'unitDelayMinGrupo',
    unitDelayMaxId: 'unitDelayMaxGrupo',
    complianceModeId: 'complianceModeGroups',
    riskProfileId: 'riskProfileGroups',
    riskIndicatorId: 'riskIndicatorGroups',
    riskReasonId: 'riskReasonGroups',
    riskSuggestionId: 'safeSuggestionGroups',
    riskScoreId: 'riskScoreGroups',
    applySafeConfigId: 'applySafeConfigGroups',
    targetCounterId: 'targetCounterGroups',
    clearSentTargetsId: 'clearSentGroups',
    sendFilesFirstId: 'sendFilesFirstGroups',
    sendTextFirstId: 'sendTextFirstGroups',
    sendMessageSplitId: 'sendMessageSplitGroups',
    sendMessageSplitOptionId: 'sendMessageSplitOptionGroups',
    maxFiles: 3,
    progressLabel: 'Enviando mensajes a grupos...',
    successLabel: 'mensajes enviados a grupos'
  }
};

module.exports = modeConfig;
